In [3]:
import numpy as np

l =[1, 2, 3]

a = np.array (l)

print(l)
print(a)

[1, 2, 3]
[1 2 3]


In [4]:
l2 = np.array ([[1, 2], [3, 4]])
a2 = ([1,2], [3,4])

print(l2)
print(a2)

[[1 2]
 [3 4]]
([1, 2], [3, 4])


In [5]:
### Arrays de ceros y unos

zeros_array = np.zeros((2,3))
ones_array = np.ones((3,2))

print("Zeros array:\n", zeros_array)
print("Ones Arrays:\n", ones_array)

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Arrays:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
## Arrays de rangos

range_array = np.arange(10)
print("Range Array:", range_array)

Range Array: [0 1 2 3 4 5 6 7 8 9]


In [7]:
## Arrays espaciados linealmente

linspace_array = np.linspace(0, 1, num = 5)

print("Linspace: ", linspace_array)

Linspace:  [0.   0.25 0.5  0.75 1.  ]


In [8]:
## Matriz identidad

identity_matrix = np.eye(4)

print("Identity Matrix:\n", identity_matrix)

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
